us_states = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY'
}

regions = ['Africa', 'Asia', 'Europe', 'North America', 'Oceania', 'South America']

visa_color_pickers = [
            {"backgroundColor": "rgba(150,0,0,1)", "hoverBackgroundColor": "rgba(255,0,0,1)"},
            {"backgroundColor": "rgba(0,150,0,1)", "hoverBackgroundColor": "rgba(0,255,0,1)"},
            {"backgroundColor": "rgba(0,0,150,1)", "hoverBackgroundColor": "rgba(0,0,255,1)"},
            {"backgroundColor": "rgba(150,150,0,1)", "hoverBackgroundColor": "rgba(255,255,0,1)"},
            {"backgroundColor": "rgba(0,150,150,1)", "hoverBackgroundColor": "rgba(0,255,255,1)"},
            {"backgroundColor": "rgba(150,0,150,1)", "hoverBackgroundColor": "rgba(255,0,255,1)"}
        ]